### ISSUE TITLE
Wrong link here

### ISSUE THREAD

**Issue by Senorsen** [zhanghai/resume.zhanghai.me#1]
https://github.com/DreaminginCodeZH/resume.zhanghai.me/blob/d12b8c1e8560bc598009b4e88cadf8ee183f37e3/index.html#L50

**Comment by zhanghai** [comment]
Thanks, fixed. But issues should go to DreaminginCodeZH/resume .

**Comment by Senorsen** [comment]
Issue area is not opened in DreamingCodeZH/resume...

**Comment by zhanghai** [comment]
Err... I forked that repo, so that setting is inherited... Opened now anyway~
